## Todo Este proyecto fue adaptado de:
# http://josejuansanchez.org/iot-dashboard/
version: '3.1'

services:
    mosquitto:
        image: eclipse-mosquitto:2.0.10
        restart: always
	container_name: eclipse-mosquitto
        ports: 
            - 1885:1883  
        volumes:
            - ./mosquitto/config:/mosquitto/config
            - ./mosquitto/data:/mosquitto/data
            - ./mosquitto/log:/mosquitto/log
    
    telegraf: 
        image: telegraf:1.18.3
        restart: always
	container_name: telegraf 
        volumes:
            - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf 
        depends_on: 
            - influxdb
    

    
    influxdb:
        image: influxdb:1.8
        restart: always
	container_name: influxdb
        ports: 
            - 8086:8086
        volumes: 
            - ./influxdb_data:/var/lib/influxdb
        environment: 
            - INFLUXDB_DB=esteban_db
            - INFLUXDB_ADMIN_USER=root
            - INFLUXDB_ADMIN_PASSWORD=root
            - INFLUXDB_HTTP_AUTH_ENABLED=true
            
    grafana: 
        image: grafana/grafana:7.5.7 
	container_name: grafana
        restart: always
        ports:
            - 3000:3000 
        volumes:
            - grafana-storage3:/var/lib/grafana  
        depends_on: 
            - influxdb
volumes:
    grafana-storage3:
        external: false
            

# En un archivo config/mosquitto.conf agregar:

#listener 1883 0.0.0.0
#allow_anonymous true
#persistence true
#persistence_location /mosquitto/data/
#log_dest file /mosquitto/log/mosquitto.log
 
