version: '3.1'
services:
  duckdns:
    image: linuxserver/duckdns:version-6b959acf
    environment:
      - TZ=Europe/London
      - SUBDOMAINS=raspi3embpro
      - TOKEN=364c6eb6-418a-4bb4-b80f-79025f21d6b8
      - LOG_FILE=false #optional
    restart: always

