version: "2"
services:
  duckdns:
    image: linuxserver/duckdns
    #container_name: duckdns
    environment:
      - TZ=Europe/London
      - SUBDOMAINS=raspberrypi3sistemasembebidos #subdomain2
      - TOKEN=364c6eb6-418a-4bb4-b80f-79025f21d6b8
      - LOG_FILE=false #optional
    volumes:
      - ./config:/config #optional
    restart: unless-stopped