## Todo Este proyecto fue adaptado de:
# http://josejuansanchez.org/iot-dashboard/
# para montar es: sudo docker-compose up -d
version: '3.1'

services:
    mosquitto:
        image: eclipse-mosquitto:2.0.10
        restart: always
        ports: 
            - 1883:1883  
        volumes:
            - ./BaseDatos/mosquitto/config:/mosquitto/config
            - ./BaseDatos/mosquitto/data:/mosquitto/data
            - ./BaseDatos/mosquitto/log:/mosquitto/log
    
    telegraf: 
        image: telegraf:1.18.3
        restart: always
        volumes:
            - ./BaseDatos/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf
        depends_on: 
            - influxdb
    

    
    influxdb:
        image: influxdb:1.8
        restart: always
        ports: 
            - 8086:8086
        volumes: 
            - ./BaseDatos/influxdb_data:/var/lib/influxdb
        environment: 
            - INFLUXDB_DB=esteban_db
            - INFLUXDB_ADMIN_USER=admin
            - INFLUXDB_ADMIN_PASSWORD=admin
            - INFLUXDB_HTTP_AUTH_ENABLED=true
            
    grafana: 
        image: grafana/grafana:7.5.7 
        restart: always
        ports:
            - 3000:3000 
        volumes:
            - grafana-storage:/var/lib/grafana  
        depends_on: 
            - influxdb
    
    ser_brokerconection:
        build: ./BrokerMqttPython/BrokerConection
        #container_name: brokerconection:1.0
        volumes: 
        - ./BrokerMqttPython/samples:/usr/src/app/samples
        restart: always

    ser_generadoraudio:
        build: ./BrokerMqttPython/generadorAudio
        #container_name: brokerconection:1.0
        volumes: 
        - ./BrokerMqttPython/samples:/usr/src/app/samples
        restart: always

volumes:
    grafana-storage:
        external: false
            

# En un archivo config/mosquitto.conf agregar:

#listener 1883 0.0.0.0
#allow_anonymous true
#persistence true
#persistence_location /mosquitto/data/
#log_dest file /mosquitto/log/mosquitto.log

## entrar a la base de datos 
#influx -username admin -password admin
#show databases
#use esteban_db
#show measurements
#select * from mqtt_consumer
