# Se crea por defecto un alias de cada docker con el nombre del servicio
# Para ejecutarla: sudo docker-compose up -d
# Mirar donde se está ejecutando sudo docker logs 'test_app'

version: '3.1'

services:
  ser_brokerconection:
    build: ./BrokerConection
    #container_name: brokerconection:1.0
    volumes: 
      - ./samples:/usr/src/app/samples
    restart: always

  ser_generadoraudio:
    build: ./generadorAudio
    #container_name: brokerconection:1.0
    volumes: 
      - ./samples:/usr/src/app/samples
    restart: always
    

    
        